### ISSUE TITLE
Enhancement : this site have by default favicon

### ISSUE THREAD

**Issue by chaitanyakatore** [PatilHarshh/SSBT-Tech#7]
- this site contain by default favicon by REACT
<img width="575" alt="Screenshot 2023-10-25 at 11 10 02 AM" src="https://github.com/PatilHarshh/SSBT-Tech/assets/106269976/ae9531d6-9621-40f6-b0b0-6f50ddd5cb4b">

**Comment by Ashok-Kumar-dharanikota** [comment]
Hi @chaitanyakatore 

I would like to fix this issue. replacing the default icon with SSBT's logo.

**Comment by chaitanyakatore** [comment]
@Ashok-Kumar-dharanikota I'm really sorry already made PR for this try another issue

**Comment by Ashok-Kumar-dharanikota** [comment]
No problem. 😊👍
